repos:
- repo: https://github.com/psf/black
  rev: 24.8.0  # Use the latest stable version or pin a specific version
  hooks:
  - id: black
    args: [--line-length=120]  # Optional: customize Black arguments

